### PR TITLE
Fix #2: Change Bugzilla button to "View in Bugzilla" when bug exists.

### LINKED ISSUE #2: Change "File in Bugzilla" to "View in Bugzilla" when bug already exists
The file a bug button should be smart enough to know when it was already used to file a bug in Bugzilla. If it finds a matching bug, it should change to a "View in Bugzilla" button to avoid double-filings.

Maybe the text should include the bug number? Like "View Bug 1234567".

### PR DESCRIPTION
**Pull request by Osmose**
Also includes some significant refactoring to make things a little easier to
read.

@mythmon r?

### CODE REVIEW

File: content.js [hunk 1]
```diff
@@ -2,7 +2,139 @@ const ISSUE_URL_REGEX = (
...
+      console.error(err);
+    }
+  },
+
+  async getBugsForIssue(issueId) {
+      const url = new URL('https://bugzilla.mozilla.org/rest/bug');
+      url.searchParams.set('whiteboard', `[nightly-js-sentry:${issueId}]`);
+
+      if (!this.bugCache.has(issueId)) {
+        const data = await this._get(url.href);
```
Comment (mythmon) [inline content.js:65]: I'm worried about error handling here. If `_get` has a problem it returns undefined, which would then get cached, right? That doesn't seem good to me.

**Review by mythmon — CHANGES_REQUESTED** [review]
I have a question about error handling, but this looks pretty straight forward otherwise.

File: content.js (hunk 1 above)
Comment (Osmose) [reply content.js:65]: This particular function is fine because it checks that `data` is truthy before storing it in the cache, but the event/issue fetching functions don't do the same, so I updated them to not cache `undefined`, and the bug URL function to check if they're defined before using them.

**Comment by Osmose** [comment]
Updated, ready for another quick look?

**Review by mythmon — APPROVED** [review]
Looks good!

**Comment by Osmose** [comment]
Thanks!
